### ISSUE TITLE
how to count all session in global manage?

### ISSUE THREAD

**Issue by 0x457** [icza/session#1]

**Comment by icza** [comment]
This functionality is not published.

Logically the global / live session count belongs to the [`Store`](https://godoc.org/github.com/icza/session#Store). But it is not possible to tell number of sessions in some implementations (e.g. [GAE memcache store](https://github.com/icza/session/blob/master/gae_memcache_store.go)).

**Comment by nerney** [comment]
is there any way to access all the sessions in the store?
say, if i wanted to go through and remove all the sessions with some attribute?

**Comment by icza** [comment]
No, there is not.

If you need this, write / provide your own implementation of the [`Store`](https://godoc.org/github.com/icza/session#Store) interface, where you will naturally have the session collection. Be sure you make it safe for concurrent use.
