### ISSUE TITLE
Session only works...

### ISSUE THREAD

**Issue by bryku** [icza/session#15]
I am not sure if it is supposed to work this way, but sessions clear when I goto a page they are not implemented on.

Example:

/search
/login  (session implemented)
/user_stuff (session implemented)
/user_stuff_2 (session implemented)

If a user logs in with the session and goes to /user_stuff everything works fine.
It also works when they goto user_stuff_2 and back and forth.  There is no issues it is actually pretty awesome, but I have a problem if at any point the user goes to /search where the sessions are not implemented it will clear the session and if they goto /user_stuff they will not be logged in. I have tried this a few different ways but it seems to always clear the session. 
I can fix this by implementing session on the search page for kicks, but I would have a lot of pages I need to add this to. 

Is this typical behavior or is it something else on my end that is acting funny?
Are there any typical work arounds?

**Comment by icza** [comment]
If you don't work with a session in a handler, that shouldn't change the session (shouldn't clear / delete it).

Do you do any session-related task in `/search`?

**Comment by bryku** [comment]
Sorry for the late reply.  No I don't have it in search.  I can add it and it will work, but I have a lot of pages to apply it to, so I ended up making my own solution that has seemed to work just fine for now.

However, I did end up using icza/session for another project.  Thanks for the hard work.

**Comment by icza** [comment]
Glad it is resolved. Closing this then.
