### ISSUE TITLE
memcacheStore Get load logic wrong

### ISSUE THREAD

**Issue by tobytraylor** [icza/session#2]
You need to swap After to Before

```
if e.Expires.Before(time.Now()) {
   // Session expired.
   datastore.Delete(s.ctx, key) // Omitting error check...
   return nil
}
```

Effect of the current code is always to delete a valid session if the memcache is cleared.

**Comment by icza** [comment]
Are you sure?

`e.Expires` is the time instance when the session expires. `e.Expires.After(time.Now())` tells if the time when session should expire is after the current time. So if session expires 10 minutes from now, `e.Expires.After(time.Now())` will be `false`, telling it has not yet expired. If session expired 10 minutes in the past, above expression will return `true`, telling session expired and can be removed from the Datastore. I think the logic is correct.

**Comment by icza** [comment]
Thanks for reporting this. Fixed, see commit https://github.com/icza/session/commit/aea28a6e86c0685584353ce4f2af4f0d8d199e0c

**Comment by tobytraylor** [comment]
Yep.  I'm sure.  Just test it.  Clear the cache and watch it.

The value returned from your example below would be true.  I'm using s
modified version in production to fix the issue.
T

**Comment by tobytraylor** [comment]
Oh.  And thanks for writing this.  Saved me tons of time.  Good stuff!

Toby

**Comment by icza** [comment]
Hey Toby, the post you were replying above was written in haste and since then has been deleted. You were right, and I already changed that and committed. Thanks again.

**Comment by tobytraylor** [comment]
Yea.  Realized my phone had been disconnected after i wrote it but didn't
think to delete the email from my outbox.  Thanks for fixing and thanks for
the project!

Toby
