### ISSUE TITLE
Proposal: Releases

### ISSUE THREAD

**Issue by rumyantseva** [icza/session#8]
Could you please add [releases](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases) for stable versions of code? It will be easier to deal with vendoring in this case.

**Comment by icza** [comment]
I have no problem with this, I support this.

There weren't API changes or big enhancements so far, so this wasn't needed. Should there be any of those in the future, Semver2 tagging will be used.

**Comment by icza** [comment]
Actually, revisiting the history, there was a recent, important change. But that only involved the GAE support (non-GAE related parts were not affected).

Anyway, created a [v1.0.0](https://github.com/icza/session/releases/tag/v1.0.0) release pointing to the old GAE API implementation, and a [v1.1.0](https://github.com/icza/session/releases/tag/v1.1.0) release pointing to the current implementation (which uses the new GAE API).

**Comment by rumyantseva** [comment]
Thank you! 👍
